[package]
name = "regolith"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
regex = "1.10.2"
regex-macro = "0.2.0"
